# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    JNI_PATH: .
    CORENAME: dosbox_pure

# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################
  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'

  # Windows 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-i686-mingw.yml'

  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'

  # Linux 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-i686.yml'

  # MacOS 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-x64.yml'

  # MacOS ARM 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-arm64.yml'

  ################################## CELLULAR ################################
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-jni.yml'

  # iOS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ios-arm64.yml'

  # iOS (armv7)
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ios9.yml'

  ################################## CONSOLES ################################
  # Nintendo 3DS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ctr-static.yml'

  # Nintendo WiiU
  - project: 'libretro-infrastructure/ci-templates'
    file: '/wiiu-static.yml'

  # Nintendo Switch
  - project: 'libretro-infrastructure/ci-templates'
    file: '/libnx-static.yml'

  # PlayStation Vita
  - project: 'libretro-infrastructure/ci-templates'
    file: '/vita-static.yml'

  # OpenDingux
  - project: 'libretro-infrastructure/ci-templates'
    file: '/dingux-mips32.yml'

  # OpenDingux (ARM)
  - project: 'libretro-infrastructure/ci-templates'
    file: '/dingux-arm32.yml'

  # tvOS (AppleTV)
  - project: 'libretro-infrastructure/ci-templates'
    file: '/tvos-arm64.yml'

##############################################################################
#################################### STAGES ##################################
##############################################################################

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .libretro-windows-x64-mingw-make-default
    - .core-defs
  variables:
    ISWIN: 1

# Windows 32-bit
libretro-build-windows-i686:
  extends:
    - .libretro-windows-i686-mingw-make-default
    - .core-defs
  variables:
    ISWIN: 1

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .libretro-linux-x64-make-default
    - .core-defs

# Linux 32-bit
libretro-build-linux-i686:
  extends:
    - .libretro-linux-i686-make-default
    - .core-defs

# MacOS 64-bit
libretro-build-osx-x64:
  extends:
    - .libretro-osx-x64-make-default
    - .core-defs
  variables:
    ISMAC: 1

# MacOS ARM 64-bit
libretro-build-osx-arm64:
  extends:
    - .libretro-osx-arm64-make-default
    - .core-defs
  variables:
    ISMAC: 1

################################### CELLULAR #################################
# Android ARMv7a
android-armeabi-v7a:
  extends:
    - .libretro-android-jni-armeabi-v7a
    - .core-defs

# Android ARMv8a
android-arm64-v8a:
  extends:
    - .libretro-android-jni-arm64-v8a
    - .core-defs

# Android 64-bit x86
android-x86_64:
  extends:
    - .libretro-android-jni-x86_64
    - .core-defs

# Android 32-bit x86
android-x86:
  extends:
    - .libretro-android-jni-x86
    - .core-defs

# iOS
libretro-build-ios-arm64:
  extends:
    - .libretro-ios-arm64-make-default
    - .core-defs

# iOS (armv7) [iOS 9 and up]
libretro-build-ios9:
  extends:
    - .libretro-ios9-make-default
    - .core-defs
    
# tvOS
libretro-build-tvos-arm64:
  extends:
    - .libretro-tvos-arm64-make-default
    - .core-defs

#################################### CONSOLES #################################
## Nintendo 3DS
#libretro-build-ctr:
#  extends:
#    - .libretro-ctr-static-retroarch-master
#    - .core-defs

## Nintendo WiiU
#libretro-build-wiiu:
#  extends:
#    - .libretro-wiiu-static-retroarch-master
#    - .core-defs

# Nintendo Switch
libretro-build-libnx-aarch64:
  extends:
    - .libretro-libnx-static-retroarch-master
    - .core-defs

# PlayStation Vita
libretro-build-vita:
  extends:
    - .libretro-vita-static-retroarch-master
    - .core-defs

# OpenDingux
libretro-build-dingux-mips32:
  extends:
    - .libretro-dingux-mips32-make-default
    - .core-defs

# OpenDingux Beta
libretro-build-dingux-odbeta-mips32:
  extends:
    - .libretro-dingux-odbeta-mips32-make-default
    - .core-defs

# Miyoo
libretro-build-miyoo-arm32:
  extends:
    - .libretro-miyoo-arm32-make-default
    - .core-defs

# RS90 and RetroFW fail with compile errors in risc_mipsel32.h so disable them
## OpenDingux Beta
#libretro-build-rs90-odbeta-mips32:
#  extends:
#    - .libretro-rs90-odbeta-mips32-make-default
#    - .core-defs
#
## RetroFW
#libretro-build-retrofw-mips32:
#  extends:
#    - .libretro-retrofw-mips32-make-default
#    - .core-defs
